[package]
name = "threed"
version = "0.1.0"
edition = "2024"

[features]
default = ["sdl3"]

image_types = ["dep:image"]
sdl3 = ["dep:sdl3"]

[dependencies]
image = { version="0.25.6", optional = true }
rand = "0.9.1"
sdl3 = { version="0.14.31", optional = true }
